### ISSUE TITLE
Graylog cannot connect to Elasticdb

### ISSUE THREAD

**Issue by stieler-it** [beatcracker/rancher-graylog#3]
When deploying the stack in our Rancher environment, the log of the graylog container always prints:

`2.8.2017 02:01:512017-08-02 00:01:51,542 ERROR: org.graylog2.indexer.cluster.Cluster - Couldn't read cluster health for indices [graylog_*] (Could not connect to http://127.0.0.1:9200)`

It seems to be wrong to contact 127.0.0.1, right should be mongo:9200 but I didn't find the place to configure the address.

**Comment by beatcracker** [comment]
Thanks for reporting this issue. I haven't launched Graylog using this config lately, so I'll have to check.

**Comment by rhrpr** [comment]
@beatcracker @stieler-it  same here. 
```
22/08/2017 13:34:562017-08-22 12:34:56,360 ERROR: org.graylog2.indexer.cluster.Cluster - Couldn't read cluster health for indices [graylog_*] (Could not connect to http://127.0.0.1:9200)
22/08/2017 13:34:562017-08-22 12:34:56,360 INFO : org.graylog2.periodical.IndexerClusterCheckerThread - Indexer not fully initialized yet. Skipping periodic cluster check.
22/08/2017 13:35:012017-08-22 12:35:01,104 WARN : org.graylog2.bindings.providers.DefaultStreamProvider - Unable to load default stream, tried 4981 times, retrying every 500ms. Processing is blocked until this succeeds.
```

Might be something to do with the custom init script
```
 echo 'Starting custom init script...' ; IP=$$(curl -s http://rancher-metadata/latest/self/host/agent_ip) ; if [[ ! -z "$$IP" ]] ; then
        echo "Configuring 'rest_transport_uri' to use Rancher's host IP: $$IP" ;
        sed -i -E "s@#(rest_transport_uri).*@\1 = http://$$IP:$$REST_TRANSPORT_URI_PORT/api/@g" ./data/config/graylog.conf ;
      fi ;
```

**Comment by beatcracker** [comment]
Looks like Graylog needs `elasticsearch_host` to be set in config explicitly now.

Try adding this env. var to your `docker-compose.yml` or Rancher and upgrade/recreate Graylog service:

* `docker-compose.yml`

```yml
environment:
  GRAYLOG_ELASTICSEARCH_HOSTS: 'http://elasticsearch:9200'
```

* Rancher UI

![graylog2](https://user-images.githubusercontent.com/7583050/29568233-65848dc4-8758-11e7-9e3b-2b3a9075268a.PNG)

This works for me and if it does for you, I'll update `docker-compose.yml` in repo.

**Comment by rhrpr** [comment]
Nicely done - that was my suspicion as well, but I was struggling to set this (busy meddling with the graylog.conf in container rather than setting in compose).

Works for me!

**Comment by stieler-it** [comment]
Yes, works for me as well

**Comment by Anthold** [comment]
Worked for me too, thanks !
